export const COUNTRY_OPTIONS = [
  'Bangladesh',
  'United States',
  'United Kingdom',
  'India',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'United Arab Emirates',
  'Saudi Arabia',
  'Singapore',
  'Malaysia',
  'Japan',
  'China',
  'Nepal',
  'Pakistan',
  'Sri Lanka',
];
